/**
 * Geschlossene Fehlercode-Union (55_Architektur.md §10.1, ADR-016, ADR-024).
 *
 * `ALLE_FEHLERCODES` ist die einzige Quelle der Wahrheit; `FehlerCode` wird daraus abgeleitet,
 * damit die Liste und die Union nie auseinanderlaufen können. Ein neuer Fehlercode braucht eine
 * Änderung genau hier — kein `code: string`, in dem Rechtschreibvarianten koexistieren.
 */
export const ALLE_FEHLERCODES = [
  'IPC_UNBEKANNTER_KANAL',
  'IPC_UNGUELTIGE_NUTZLAST',

  'VALIDIERUNG_PFLICHTFELD',
  'VALIDIERUNG_WERTEBEREICH',
  'VALIDIERUNG_DATUM_UNLESBAR',
  'VALIDIERUNG_ORTSWERT',

  'NICHT_GEFUNDEN_PERSON',
  'NICHT_GEFUNDEN_ORT',
  'NICHT_GEFUNDEN_TRANSAKTION',
  'NICHT_GEFUNDEN_NAME',
  'NICHT_GEFUNDEN_ELTERNSCHAFT',
  'NICHT_GEFUNDEN_PARTNERSCHAFT',
  'NICHT_GEFUNDEN_EREIGNIS',
  'NICHT_GEFUNDEN_BETEILIGUNG',
  'NICHT_GEFUNDEN_AUSSAGE',
  'NICHT_GEFUNDEN_ZITAT',
  'NICHT_GEFUNDEN_AUSSAGE_ZITAT',
  'NICHT_GEFUNDEN_ORTSNAME',
  'NICHT_GEFUNDEN_ORTSZUGEHOERIGKEIT',
  'NICHT_GEFUNDEN_ORT_EXTERNE_ID',
  'NICHT_GEFUNDEN_ARCHIV',
  'NICHT_GEFUNDEN_QUELLE',
  'NICHT_GEFUNDEN_NEGATIVBEFUND',

  'KONFLIKT_ZYKLUS',
  'KONFLIKT_ZYKLUS_ORT',
  'KONFLIKT_BEREITS_VORHANDEN',
  'KONFLIKT_ORT_EXTERNE_ID_DUPLIKAT',
  'BEFEHL_VERSCHACHTELT',

  'JOURNAL_NICHTS_ZURUECKZUNEHMEN',
  'JOURNAL_NICHTS_WIEDERHOLBAR',
  'JOURNAL_NICHT_RUECKNEHMBAR',

  'DATENBANK_GESPERRT',
  'DATENBANK_FREMDSCHLUESSEL',
  'DATENBANK_INTEGRITAET',

  'PROJEKT_BEREITS_GEOEFFNET',
  'PROJEKT_KEIN_WURZELWERK_ORDNER',
  'PROJEKT_NEUERE_SCHEMAVERSION',
  'PROJEKT_MIGRATION_GEAENDERT',
  'PROJEKT_NICHT_GEOEFFNET',
  'PROJEKT_NAME_UNGUELTIG',

  'DATEI_NICHT_LESBAR',
  'DATEI_KEIN_PLATZ',

  'IMPORT_VERTRAG_UNBEKANNT',
  'IMPORT_SCHEMA_FEHLER',
  'IMPORT_REFERENZ_FEHLT',
  'IMPORT_MEDIUM_NICHT_KOPIERBAR',
  'IMPORT_SCHNAPPSCHUSS_FEHLGESCHLAGEN',

  'INTERN_UNERWARTET',
] as const

export type FehlerCode = (typeof ALLE_FEHLERCODES)[number]
